<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IL-0908" name="com.deere.testCases.US32633_AuditTrails" tests="1" failures="0" timestamp="18 May 2018 06:54:27 GMT" time="137.512" errors="1">
  <testcase name="test_AuditTrailDetails" time="137.512" classname="com.deere.testCases.US32633_AuditTrails">
    <error type="java.lang.AssertionError" message="Navigate to gsc page displayed successfully expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Navigate to gsc page displayed successfully expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.deere.global.CommonFunctions.assertTrue(CommonFunctions.java:1083)
	at com.deere.testCases.US32633_AuditTrails.test_AuditTrailDetails(US32633_AuditTrails.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- test_AuditTrailDetails -->
</testsuite> <!-- com.deere.testCases.US32633_AuditTrails -->
